### ISSUE TITLE
3-improving.md中的vertexPosition没有申明，4-directional-lighting.md中的Enhanced directional lighting中的代码块存在语法问题

### ISSUE THREAD

**Issue by Pycnocline** [IrisShaders/ShaderDoc#19]
getting-started中可能存在两个问题：

1.在3-improving.md文件中的Back to the Fragment shader (again)部分存在以下代码：
```
float fogValue = vertexPosition < fogEnd ? smoothstep(fogStart, fogEnd, vertexPosition) : 1.0;
```
此代码中的`vertexPosition`没有在上下文中提及且没有声明，推测应该为`vertexDistance`

2.在4-directional-lighting.md中的Enhanced directional lighting部分存在以下代码：
```
float NdotL = max(0.2, dot(normal, normalize(shadowLightPosition));
```
此代码中缺少一个')'

**Comment by WGrav01** [comment]
Translated to English:

>  There are two possible problems in getting-started:
> 
> 1. The following code exists in the Back to the Fragment shader (again) section of the 3-improving.md file:
> 
> 
> 
> `float fogValue = vertexPosition < fogEnd ? smoothstep(fogStart, fogEnd, vertexPosition) : 1.0;`
> 
> The `vertexPosition` in this code is not mentioned in the context and is not declared, presumably it should be `vertexDistance`.
> 
> 2. The following code exists in the Enhanced directional lighting section of 4-directional-lighting.md:
> 
> `float NdotL = max(0.2, dot(normal, normalize(shadowLightPosition));`
> 
> This code is missing a single ')'.

**Comment by WGrav01** [comment]
The first error was fixed in PR https://github.com/IrisShaders/ShaderDoc/pull/18, ~~I'll open another PR to fix the second issue.~~ (Fixed in https://github.com/IrisShaders/ShaderDoc/pull/20)
